### PR TITLE
Add PNG file extension

### LINKED ISSUE #9: Files being saved without an extension
I don't know if it's just on my end, but whenever I capture a screenshot, it gets saved without an extension.
This makes it unusable (both unopenable and unshareable) until I manually open a file explorer app and rename the file to append ".jpg".

Oh, and I'm on android 6.0, using Sharedr as the share menu. I just installed your app through F-Droid.

BTW, nice app. My phone's buttons are messed up, and I needed an assistant app that saves screenshots instead of just sharing them.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/rosenpin/screenshot-sharer/issues/9

### CODE REVIEW

**Comment by ghost** [comment]
Additionally, as screenshots captured in PNG why there `image/jpeg` MIME-Type used in few places?

- https://github.com/rosenpin/screenshot-sharer/blob/6b57f7a9acb5c08e1f67d19906a61285402106b9/app/src/main/java/com/tomer/screenshotsharer/AssistLoggerSession.kt#L100
- https://github.com/rosenpin/screenshot-sharer/blob/6b57f7a9acb5c08e1f67d19906a61285402106b9/app/src/main/java/com/tomer/screenshotsharer/AssistLoggerSession.kt#L156

**Comment by rosenpin** [comment]
Thanks for the PR :)

This doesn't seem right.  
On my device (Android 11) the screenshots are saved correctly as jpeg.  
Your PR would change the name of the screenshot, I didn't test it but on Android Q+ it might result in jpeg images called "screenshot-.....png.jpg"  
Please test it on an Android 11 emulator and let me know if I'm wrong.  
Alternatively, only apply your solution to old Android versions (Q- not included)

**Comment by ghost** [comment]
I'm not be able to run any emulator.

> On my device (Android 11) the screenshots are saved correctly as jpeg

But how, as app capture as PNG? Does on Android 11 it saves to folder it as JPEG? (actually on my Android 6 screenshots saves into "Pictures > Screenshots" are exactly PNG as I see in image quality & in file headers via Hex-editors)

- https://github.com/rosenpin/screenshot-sharer/blob/master/app/src/main/java/com/tomer/screenshotsharer/AssistLoggerSession.kt#L92-L118

BTW, As I see in "Screenshot Assistant" app (which is designed to store only JPEG screenshots) it uses `Screenshot-${currentDateString()}.${imageFormat.fileExtension}` for adding file extension.

- https://github.com/beatbrot/ScreenshotAssistant/blob/3d8ce0dc0e2580a6ba55d3379654b67ad79d9112/app/src/main/java/de/beatbrot/screenshotassistant/ScreenshotActivityViewModel.kt#L71
- https://github.com/beatbrot/ScreenshotAssistant/issues/75

**Comment by rosenpin** [comment]
Thanks for the detailed response.  
Seems like you're right  
image

I'm not sure because I really don't remember a whole lot from this project, but I assume this line should be changed: 
https://github.com/rosenpin/screenshot-sharer/blob/6b57f7a9acb5c08e1f67d19906a61285402106b9/app/src/main/java/com/tomer/screenshotsharer/AssistLoggerSession.kt#L100

And potentially also this:
https://github.com/rosenpin/screenshot-sharer/blob/6b57f7a9acb5c08e1f67d19906a61285402106b9/app/src/main/java/com/tomer/screenshotsharer/AssistLoggerSession.kt#L156

Otherwise I really don't know where the `.jpg` suffix appear on my device

**Comment by ghost** [comment]
Thanks! May you add also `app-release.apk` asset to `2.0` release?
Can't wait to test! (F-Droid packaging is slow)

**Comment by rosenpin** [comment]
Actually I lost the keystore for this app, that's the reason the play store version is outdated by the way.  
I'll upload an unsigned version of the app

**Comment by rosenpin** [comment]
https://github.com/rosenpin/screenshot-sharer/releases/download/2.1/app-debug.apk

**Pull request merged**
